### ISSUE TITLE
chalk properties are still exposed

### ISSUE THREAD

**Issue by cpiber** [chalk/chalk-template#12]
`chalk-template` provides a separate way to use `chalk`. The highlighting properties (e.g. `chalk.red`) are not intended to be used, but they are still available. They work, but break on ttys (see chalk/chalk#568).

**Comment by Qix-** [comment]
> They work, but break on ttys

Can you elaborate a bit on this?

**Comment by cpiber** [comment]
I apologize. This was my mistake, I realized during testing.
