### ISSUE TITLE
Use chalk-template with a custom chalk instance

### ISSUE THREAD

**Issue by lukekarrys** [chalk/chalk-template#16]
Taking a quick look at the code, I don’t think this is possible currently.

It would be helpful if both `makeTemplate` and `makeChalkTemplate` were exported so I could do the following:

```js
import {Chalk} from 'chalk'
import {makeTemplate, makeChalkTemplate} from 'chalk-template'

const chalk = new Chalk({ level: 0  })
const chalkTemplate = makeChalkTemplate(makeTemplate(chalk))

console.log(chalkTemplate`{red Hi!}`)
```

The code above should print `Hi!` with no coloring. This is a silly example, but I would like a way to write strings with predefined colors and also be able to pass those strings to a template function that would remove them. This would also be possible by using the regexes in the source to strip colors, but the way in my example seems easier to write.

Also for my use case, I would want to use both functions together, so a single export that wraps `makeChalkTemplate(makeTemplate())` would be nice, but not required.

**Comment by Qix-** [comment]
I thought we already had this, huh. I'm on mobile about to go to bed, but a PR is of course welcome.

**Comment by lukekarrys** [comment]
Thank you! I opened the issue to make sure I wasn't missing anything first. PR incoming.
