### ISSUE TITLE
Use raw length instead of escaped length when traversing string parts

### ISSUE THREAD

**Issue by Qix-** [chalk/chalk-template#5]
Easy fix but I don't have time for it at the moment. Just need to remember to do it at some point, or allow someone else to do it at some point.

https://github.com/chalk/chalk-template/blob/6e63a466ba254b779587b0ca0ad5570588a4c238/index.js#L164

Instead of `firstString.length` it needs to be `firstString.raw.length`.

In fact, `firstString` is a misnomer here, dunno if I wrote that or if that got changed but it's not right. Template functions are weird and take an array as the first parameter, which itself has a property called `.raw` that is also an array (of the same arity) with the _unescaped_ strings. The latter is what `chalk-template` uses.

Therefore, the entire thing can just be summarized as `const rawStrings = strings.raw` and use `rawStrings` for everything. Feel free to make that change.

Also change `arguments_` back to `args`. If XO complains, ping me. There is no reason to use a `_` postfix here to appease the builtin check. Alternatively, just call it `values`.

PR welcome, would be swiftly merged. Great beginner fix!

**Comment by billymoroney1** [comment]
hey @Qix- was looking for an issue and put in a PR -

**Comment by Qix-** [comment]
Thank you ^^
