### ISSUE TITLE
Is there anyway to pass a programmatically built string in?

### ISSUE THREAD

**Issue by ratacat** [chalk/chalk-template#7]
```javascript
import { Chalk } from "chalk";
const chalk = new Chalk({ level: 3 });
import chalkTemplate from "chalk-template";
import { convertToChalk } from "./convertToChalk.js";

const block = `A deep well of <c="#E56399">transylexic</c> <color value="silver">ambiphobia</color> pulses in and out of existence. What was in that potion?!`;
const templateString = convertToChalk(block);
console.log(chalkTemplate`${templateString}`); //this doesn't work

console.log(
  chalkTemplate`A deep well of {#E56399 transylexic} {#E56399 ambiphobia} pulses in and out of existence. What was in that potion?!`
); //this works fine, both strings are the same
```
So I am trying to write a little script to automatically output some strings with custom color tags to the terminal. So my convertToChalk function is correctly formatting the template string, but I'm having trouble getting chalkTemplate to interpret it. If I pass the string in 'raw' not as a variable, it works fine.

Any suggestions or insights would be greatly appreciated! I'm sure I"m just not understanding this.
Output looks like this
```
A deep well of {#E56399 transylexic} {#c0c0c0 ambiphobia} pulses in and out of existence. What was in that potion?!
A deep well of transylexic ambiphobia pulses in and out of existence. What was in that potion?!
```

*note* edited to remove swear word that was in my text string

**Comment by Qix-** [comment]
```javascript
const chalkTemplateFn = str => {
    const strs = [str];
    strs.raw = [str];
    return chalkTemplate(strs);
};

console.log(chalkTemplate('{#FF0000 should be red}'));
```

Give that a shot.

**Comment by ratacat** [comment]
That works awesome! Thank you so much for helping me! Is the `raw` property an element of chalk itself? Or of chalkTemplate?

**Comment by Qix-** [comment]
Neither, it's how tagged template literals work. `chalk-template` uses `raw` to be able to catch `\{`/`\}`, which causes it to ignore those characters instead of treating them like template clauses.

```javascript
const myTag = (strs, ...args) => console.log({strs, raw: strs.raw, args});

myTag`there are ${99} bottles of \nbeer on the wall`;

/*
{
  strs: [ 'there are ', ' bottles of \nbeer on the wall' ],
  raw: [ 'there are ', ' bottles of \\nbeer on the wall' ],
  args: [ 99 ]
}
*/
```

**Comment by Qix-** [comment]
Going to go ahead and close this, let me know if you have any other questions :)

**Comment by ratacat** [comment]
wow, okay, I think I understand it now. Thank you again!
